"""
Django settings for workshop_portal project.

Generated by 'django-admin startproject' using Django 1.10.4.

Production-ready version — all sensitive values driven by environment variables.
Set DJANGO_SECRET_KEY, DEBUG, ALLOWED_HOSTS, DB_*, EMAIL_* in your .env file.
Set PRODUCTION=True in production to enable security headers.
"""

import os
import dj_database_url
from decouple import config, Csv


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ─── Core ────────────────────────────────────────────────────────────────────

# SECURITY WARNING: keep the secret key used in production secret!
# Generate a new one: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"
SECRET_KEY = config('DJANGO_SECRET_KEY', default='dev-insecure-key-replace-in-production-!!!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Set PRODUCTION=True in production to enable all security headers
PRODUCTION = config('PRODUCTION', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# ─── Apps ────────────────────────────────────────────────────────────────────

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workshop_app',
    'statistics_app',
    'teams',
    'cms',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ─── Security Headers (always-on basics) ─────────────────────────────────────

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# HSTS + HTTPS — enabled only in production (set PRODUCTION=True in .env)
if PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_HSTS_SECONDS = 31536000      # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ─── URLs & WSGI ─────────────────────────────────────────────────────────────

ROOT_URLCONF = 'workshop_portal.urls'
WSGI_APPLICATION = 'workshop_portal.wsgi.application'

# ─── Templates ───────────────────────────────────────────────────────────────

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['workshop_app/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ─── Database ────────────────────────────────────────────────────────────────
# If DATABASE_URL is set (Render/Railway/Heroku), use it directly.
# Otherwise fall back to per-field env vars (local SQLite for dev).
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=PRODUCTION,  # require SSL in production
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.{0}'.format(
                config('DB_ENGINE', default='sqlite3')
            ),
            'NAME': config('DB_NAME', default=os.path.join(BASE_DIR, 'db.sqlite3')),
            'USER': config('DB_USER', default=''),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default=''),
        }
    }

# ─── Password Validation ─────────────────────────────────────────────────────

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ─── Internationalisation ────────────────────────────────────────────────────

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ─── Static & Media ──────────────────────────────────────────────────────────

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/data/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'workshop_app', 'data')

LOG_FOLDER = os.path.join(BASE_DIR, 'workshop_app', 'logs')

# ─── Email ───────────────────────────────────────────────────────────────────
# In development set EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
# In production set EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'
)
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_TIMEOUT = 300
SENDER_EMAIL = config('SENDER_EMAIL', default='noreply@example.com')

# ─── App Settings ────────────────────────────────────────────────────────────

# Change this to the production URL — used in email activation links
PRODUCTION_URL = config('PRODUCTION_URL', default='http://localhost:8000')

# Admin email for system notifications
ADMIN_EMAIL = config('ADMIN_EMAIL', default='admin@example.com')

# Set True or False to show / hide workshop statistics page
SHOW_WORKSHOP_STATS = config('SHOW_WORKSHOP_STATS', default=True, cast=bool)

# Create a CMS page as a home page and give the page title here
HOME_PAGE_TITLE = config('HOME_PAGE_TITLE', default='home-page-title')

LOGIN_URL = '/workshop/login/'
LOGIN_REDIRECT_URL = '/workshop/login'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 3600

# ─── CORS (React Frontend) ──────────────────────────────────────────────────
# Development: uses the defaults below
# Production: set CORS_ALLOWED_ORIGINS=https://yourdomain.com in .env

if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:5173',
        'http://localhost:3000',
        'http://127.0.0.1:5173',
        'http://127.0.0.1:3000',
    ]
else:
    _cors_origins = config('CORS_ALLOWED_ORIGINS', default='')
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

CORS_ALLOW_CREDENTIALS = True

# ─── Django REST Framework ───────────────────────────────────────────────────

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
